name: OCI Builds

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  oci-builds:
    name: OCI Builds
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Sync environment
        run: uv sync --locked --all-extras --dev
      - name: Build inference-gateway
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: inference-api
          tags: ${{ github.sha }}
          containerfiles: |
            ./deploy/docker/Dockerfile
          oci: true
      - name: Publish to GoHarbor
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
